"""Add BotRun Table

Revision ID: 2da98aba9992
Revises: b2c3d4e5f6a7
Create Date: 2025-10-07 12:17:50.180288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da98aba9992'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_bot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runid', sa.String(length=100), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('test_mode', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_runs_bot_name'), 'ai_bot_runs', ['bot_name'], unique=False)
    op.create_index(op.f('ix_bot_runs_cancel_requested'), 'ai_bot_runs', ['cancel_requested'], unique=False)
    op.create_index(op.f('ix_bot_runs_id'), 'ai_bot_runs', ['id'], unique=False)
    op.create_index(op.f('ix_bot_runs_runid'), 'ai_bot_runs', ['runid'], unique=True)
    op.create_index(op.f('ix_bot_runs_status'), 'ai_bot_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_runs_status'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_bot_runs_runid'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_bot_runs_id'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_bot_runs_cancel_requested'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_bot_runs_bot_name'), table_name='ai_bot_runs')
    op.drop_table('ai_bot_runs')
    # ### end Alembic commands ###



