"""Add Agent Registry

Revision ID: a83476e420e2
Revises: fbf99a635d7e
Create Date: 2025-10-24 11:46:25.500395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83476e420e2'
down_revision: Union[str, Sequence[str], None] = 'fbf99a635d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_bot_payline_items_emplid'), 'ai_bot_payline_items', ['emplid'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_ern_ded_code'), 'ai_bot_payline_items', ['ern_ded_code'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_hr_requestor'), 'ai_bot_payline_items', ['hr_requestor'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_id'), 'ai_bot_payline_items', ['id'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_month_requested'), 'ai_bot_payline_items', ['month_requested'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_site'), 'ai_bot_payline_items', ['site'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_status'), 'ai_bot_payline_items', ['status'], unique=False)
    op.create_index(op.f('ix_ai_bot_payline_items_tab_name'), 'ai_bot_payline_items', ['tab_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_bot_runs_status'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_ai_bot_runs_runid'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_ai_bot_runs_id'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_ai_bot_runs_cancel_requested'), table_name='ai_bot_runs')
    op.drop_index(op.f('ix_ai_bot_runs_bot_name'), table_name='ai_bot_runs')
    op.create_index(op.f('ix_bot_runs_status'), 'ai_bot_runs', ['status'], unique=False)
    op.create_index(op.f('ix_bot_runs_id'), 'ai_bot_runs', ['id'], unique=False)
    op.create_index(op.f('ix_bot_runs_cancel_requested'), 'ai_bot_runs', ['cancel_requested'], unique=False)
    op.create_index(op.f('ix_bot_runs_bot_name'), 'ai_bot_runs', ['bot_name'], unique=False)
    op.drop_index(op.f('ix_ai_bot_process_log_voucher_id'), table_name='ai_bot_process_log')
    op.drop_index(op.f('ix_ai_bot_process_log_status'), table_name='ai_bot_process_log')
    op.drop_index(op.f('ix_ai_bot_process_log_runid'), table_name='ai_bot_process_log')
    op.drop_index(op.f('ix_ai_bot_process_log_invoice'), table_name='ai_bot_process_log')
    op.drop_index(op.f('ix_ai_bot_process_log_id'), table_name='ai_bot_process_log')
    op.drop_index(op.f('ix_ai_bot_process_log_filename'), table_name='ai_bot_process_log')
    op.alter_column('ai_bot_process_log', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(collation='Latin1_General_BIN'),
               existing_nullable=True)
    op.alter_column('ai_bot_process_log', 'invoice',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(collation='Latin1_General_BIN'),
               existing_nullable=True)
    op.alter_column('ai_bot_process_log', 'voucher_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(collation='Latin1_General_BIN'),
               existing_nullable=True)
    op.alter_column('ai_bot_process_log', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(collation='Latin1_General_BIN'),
               existing_nullable=True)
    op.alter_column('ai_bot_process_log', 'runid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(collation='Latin1_General_BIN'),
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_bot_payline_items_tab_name'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_status'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_site'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_month_requested'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_id'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_hr_requestor'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_ern_ded_code'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_emplid'), table_name='ai_bot_payline_items')
    # ### end Alembic commands ###
