"""Add Payline table

Revision ID: fbf99a635d7e
Revises: 2da98aba9992
Create Date: 2025-10-09 14:46:11.558780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf99a635d7e'
down_revision: Union[str, Sequence[str], None] = '2da98aba9992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_bot_payline_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('hr_requestor', sa.String(length=100), nullable=True),
    sa.Column('month_requested', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=150), nullable=True),
    sa.Column('emplid', sa.String(length=50), nullable=False),
    sa.Column('empl_rcd', sa.Integer(), nullable=False),
    sa.Column('ern_ded_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('earnings_begin_dt', sa.String(length=20), nullable=True),
    sa.Column('earnings_end_dt', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_bot_payline_items_tab_name'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_status'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_site'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_month_requested'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_id'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_hr_requestor'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_ern_ded_code'), table_name='ai_bot_payline_items')
    op.drop_index(op.f('ix_ai_bot_payline_items_emplid'), table_name='ai_bot_payline_items')
    op.drop_table('ai_bot_payline_items')
    # ### end Alembic commands ###
